language: node_js
node_js:
- '0.10'
env:
  global:
    secure: PuKpWweqOljNjKmbaqtay/2RS5foYFj+nMvaB6aTAkSd8XxzsTj9cMn8gpO4zG0svVU23GIeeTJuZMr+ny0HN7lo4/vjeczKcbIETWzy7DZFU88veecbsxblVzzbBbwqfQwj6HeX/2NLQ3ajpjMzJgfjB60pKglxo20+Iamnlio=
